[package]
name = "explorer_wrangler"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61.1", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Accessibility"
] }
once_cell = "1.17"
eyre = "0.6.12"
color-eyre = "0.6.3"
