// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddSystemTrayEntryArgs {
    pub system_tray_entry_id: __sdk::Identity,
    pub system_tray_id: __sdk::Identity,
    pub icon: String,
    pub tooltip: String,
    pub text: String,
}

impl From<AddSystemTrayEntryArgs> for super::Reducer {
    fn from(args: AddSystemTrayEntryArgs) -> Self {
        Self::AddSystemTrayEntry {
            system_tray_entry_id: args.system_tray_entry_id,
            system_tray_id: args.system_tray_id,
            icon: args.icon,
            tooltip: args.tooltip,
            text: args.text,
        }
    }
}

impl __sdk::InModule for AddSystemTrayEntryArgs {
    type Module = super::RemoteModule;
}

pub struct AddSystemTrayEntryCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_system_tray_entry`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_system_tray_entry {
    /// Request that the remote module invoke the reducer `add_system_tray_entry` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_system_tray_entry`] callbacks.
    fn add_system_tray_entry(
        &self,
        system_tray_entry_id: __sdk::Identity,
        system_tray_id: __sdk::Identity,
        icon: String,
        tooltip: String,
        text: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_system_tray_entry`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddSystemTrayEntryCallbackId`] can be passed to [`Self::remove_on_add_system_tray_entry`]
    /// to cancel the callback.
    fn on_add_system_tray_entry(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &__sdk::Identity,
                &__sdk::Identity,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> AddSystemTrayEntryCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_system_tray_entry`],
    /// causing it not to run in the future.
    fn remove_on_add_system_tray_entry(&self, callback: AddSystemTrayEntryCallbackId);
}

impl add_system_tray_entry for super::RemoteReducers {
    fn add_system_tray_entry(
        &self,
        system_tray_entry_id: __sdk::Identity,
        system_tray_id: __sdk::Identity,
        icon: String,
        tooltip: String,
        text: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_system_tray_entry",
            AddSystemTrayEntryArgs {
                system_tray_entry_id,
                system_tray_id,
                icon,
                tooltip,
                text,
            },
        )
    }
    fn on_add_system_tray_entry(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &__sdk::Identity,
                &__sdk::Identity,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> AddSystemTrayEntryCallbackId {
        AddSystemTrayEntryCallbackId(self.imp.on_reducer(
            "add_system_tray_entry",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddSystemTrayEntry {
                                    system_tray_entry_id,
                                    system_tray_id,
                                    icon,
                                    tooltip,
                                    text,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    system_tray_entry_id,
                    system_tray_id,
                    icon,
                    tooltip,
                    text,
                )
            }),
        ))
    }
    fn remove_on_add_system_tray_entry(&self, callback: AddSystemTrayEntryCallbackId) {
        self.imp
            .remove_on_reducer("add_system_tray_entry", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_system_tray_entry`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_system_tray_entry {
    /// Set the call-reducer flags for the reducer `add_system_tray_entry` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_system_tray_entry(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_system_tray_entry for super::SetReducerFlags {
    fn add_system_tray_entry(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("add_system_tray_entry", flags);
    }
}
