// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddTaskbarArgs {
    pub taskbar_id: __sdk::Identity,
    pub width: u32,
    pub height: u32,
    pub x: i32,
    pub y: i32,
}

impl From<AddTaskbarArgs> for super::Reducer {
    fn from(args: AddTaskbarArgs) -> Self {
        Self::AddTaskbar {
            taskbar_id: args.taskbar_id,
            width: args.width,
            height: args.height,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for AddTaskbarArgs {
    type Module = super::RemoteModule;
}

pub struct AddTaskbarCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_taskbar`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_taskbar {
    /// Request that the remote module invoke the reducer `add_taskbar` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_taskbar`] callbacks.
    fn add_taskbar(
        &self,
        taskbar_id: __sdk::Identity,
        width: u32,
        height: u32,
        x: i32,
        y: i32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_taskbar`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddTaskbarCallbackId`] can be passed to [`Self::remove_on_add_taskbar`]
    /// to cancel the callback.
    fn on_add_taskbar(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &u32, &u32, &i32, &i32)
            + Send
            + 'static,
    ) -> AddTaskbarCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_taskbar`],
    /// causing it not to run in the future.
    fn remove_on_add_taskbar(&self, callback: AddTaskbarCallbackId);
}

impl add_taskbar for super::RemoteReducers {
    fn add_taskbar(
        &self,
        taskbar_id: __sdk::Identity,
        width: u32,
        height: u32,
        x: i32,
        y: i32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_taskbar",
            AddTaskbarArgs {
                taskbar_id,
                width,
                height,
                x,
                y,
            },
        )
    }
    fn on_add_taskbar(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &u32, &u32, &i32, &i32)
            + Send
            + 'static,
    ) -> AddTaskbarCallbackId {
        AddTaskbarCallbackId(self.imp.on_reducer(
            "add_taskbar",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddTaskbar {
                                    taskbar_id,
                                    width,
                                    height,
                                    x,
                                    y,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, taskbar_id, width, height, x, y)
            }),
        ))
    }
    fn remove_on_add_taskbar(&self, callback: AddTaskbarCallbackId) {
        self.imp.remove_on_reducer("add_taskbar", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_taskbar`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_taskbar {
    /// Set the call-reducer flags for the reducer `add_taskbar` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_taskbar(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_taskbar for super::SetReducerFlags {
    fn add_taskbar(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_taskbar", flags);
    }
}
