// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddSystemTrayArgs {
    pub system_tray_id: __sdk::Identity,
    pub taskbar_id: __sdk::Identity,
}

impl From<AddSystemTrayArgs> for super::Reducer {
    fn from(args: AddSystemTrayArgs) -> Self {
        Self::AddSystemTray {
            system_tray_id: args.system_tray_id,
            taskbar_id: args.taskbar_id,
        }
    }
}

impl __sdk::InModule for AddSystemTrayArgs {
    type Module = super::RemoteModule;
}

pub struct AddSystemTrayCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_system_tray`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_system_tray {
    /// Request that the remote module invoke the reducer `add_system_tray` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_system_tray`] callbacks.
    fn add_system_tray(
        &self,
        system_tray_id: __sdk::Identity,
        taskbar_id: __sdk::Identity,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_system_tray`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddSystemTrayCallbackId`] can be passed to [`Self::remove_on_add_system_tray`]
    /// to cancel the callback.
    fn on_add_system_tray(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &__sdk::Identity)
            + Send
            + 'static,
    ) -> AddSystemTrayCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_system_tray`],
    /// causing it not to run in the future.
    fn remove_on_add_system_tray(&self, callback: AddSystemTrayCallbackId);
}

impl add_system_tray for super::RemoteReducers {
    fn add_system_tray(
        &self,
        system_tray_id: __sdk::Identity,
        taskbar_id: __sdk::Identity,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_system_tray",
            AddSystemTrayArgs {
                system_tray_id,
                taskbar_id,
            },
        )
    }
    fn on_add_system_tray(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &__sdk::Identity)
            + Send
            + 'static,
    ) -> AddSystemTrayCallbackId {
        AddSystemTrayCallbackId(self.imp.on_reducer(
            "add_system_tray",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddSystemTray {
                                    system_tray_id,
                                    taskbar_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, system_tray_id, taskbar_id)
            }),
        ))
    }
    fn remove_on_add_system_tray(&self, callback: AddSystemTrayCallbackId) {
        self.imp.remove_on_reducer("add_system_tray", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_system_tray`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_system_tray {
    /// Set the call-reducer flags for the reducer `add_system_tray` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_system_tray(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_system_tray for super::SetReducerFlags {
    fn add_system_tray(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_system_tray", flags);
    }
}
