// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::system_tray_entry_type::SystemTrayEntry;
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

/// Table handle for the table `system_tray_entry`.
///
/// Obtain a handle from the [`SystemTrayEntryTableAccess::system_tray_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.system_tray_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_tray_entry().on_insert(...)`.
pub struct SystemTrayEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<SystemTrayEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `system_tray_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SystemTrayEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SystemTrayEntryTableHandle`], which mediates access to the table `system_tray_entry`.
    fn system_tray_entry(&self) -> SystemTrayEntryTableHandle<'_>;
}

impl SystemTrayEntryTableAccess for super::RemoteTables {
    fn system_tray_entry(&self) -> SystemTrayEntryTableHandle<'_> {
        SystemTrayEntryTableHandle {
            imp: self.imp.get_table::<SystemTrayEntry>("system_tray_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SystemTrayEntryInsertCallbackId(__sdk::CallbackId);
pub struct SystemTrayEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SystemTrayEntryTableHandle<'ctx> {
    type Row = SystemTrayEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemTrayEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SystemTrayEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemTrayEntryInsertCallbackId {
        SystemTrayEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SystemTrayEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SystemTrayEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemTrayEntryDeleteCallbackId {
        SystemTrayEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SystemTrayEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SystemTrayEntry>("system_tray_entry");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct SystemTrayEntryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SystemTrayEntryTableHandle<'ctx> {
    type UpdateCallbackId = SystemTrayEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SystemTrayEntryUpdateCallbackId {
        SystemTrayEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SystemTrayEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SystemTrayEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SystemTrayEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `system_tray_entry`,
/// which allows point queries on the field of the same name
/// via the [`SystemTrayEntryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_tray_entry().id().find(...)`.
pub struct SystemTrayEntryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SystemTrayEntry, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SystemTrayEntryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `system_tray_entry`.
    pub fn id(&self) -> SystemTrayEntryIdUnique<'ctx> {
        SystemTrayEntryIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SystemTrayEntryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<SystemTrayEntry> {
        self.imp.find(col_val)
    }
}
