// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SystemTray {
    pub system_tray_id: __sdk::Identity,
    pub taskbar_id: __sdk::Identity,
}

impl __sdk::InModule for SystemTray {
    type Module = super::RemoteModule;
}
