// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::system_tray_type::SystemTray;
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

/// Table handle for the table `system_tray`.
///
/// Obtain a handle from the [`SystemTrayTableAccess::system_tray`] method on [`super::RemoteTables`],
/// like `ctx.db.system_tray()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_tray().on_insert(...)`.
pub struct SystemTrayTableHandle<'ctx> {
    imp: __sdk::TableHandle<SystemTray>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `system_tray`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SystemTrayTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SystemTrayTableHandle`], which mediates access to the table `system_tray`.
    fn system_tray(&self) -> SystemTrayTableHandle<'_>;
}

impl SystemTrayTableAccess for super::RemoteTables {
    fn system_tray(&self) -> SystemTrayTableHandle<'_> {
        SystemTrayTableHandle {
            imp: self.imp.get_table::<SystemTray>("system_tray"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SystemTrayInsertCallbackId(__sdk::CallbackId);
pub struct SystemTrayDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SystemTrayTableHandle<'ctx> {
    type Row = SystemTray;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemTray> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SystemTrayInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemTrayInsertCallbackId {
        SystemTrayInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SystemTrayInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SystemTrayDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemTrayDeleteCallbackId {
        SystemTrayDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SystemTrayDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SystemTray>("system_tray");
    _table.add_unique_constraint::<__sdk::Identity>("system_tray_id", |row| &row.system_tray_id);
}
pub struct SystemTrayUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SystemTrayTableHandle<'ctx> {
    type UpdateCallbackId = SystemTrayUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SystemTrayUpdateCallbackId {
        SystemTrayUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SystemTrayUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SystemTray>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SystemTray>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `system_tray_id` unique index on the table `system_tray`,
/// which allows point queries on the field of the same name
/// via the [`SystemTraySystemTrayIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_tray().system_tray_id().find(...)`.
pub struct SystemTraySystemTrayIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SystemTray, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SystemTrayTableHandle<'ctx> {
    /// Get a handle on the `system_tray_id` unique index on the table `system_tray`.
    pub fn system_tray_id(&self) -> SystemTraySystemTrayIdUnique<'ctx> {
        SystemTraySystemTrayIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("system_tray_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SystemTraySystemTrayIdUnique<'ctx> {
    /// Find the subscribed row whose `system_tray_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<SystemTray> {
        self.imp.find(col_val)
    }
}
