// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::taskbar_type::Taskbar;
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

/// Table handle for the table `taskbar`.
///
/// Obtain a handle from the [`TaskbarTableAccess::taskbar`] method on [`super::RemoteTables`],
/// like `ctx.db.taskbar()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.taskbar().on_insert(...)`.
pub struct TaskbarTableHandle<'ctx> {
    imp: __sdk::TableHandle<Taskbar>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `taskbar`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TaskbarTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TaskbarTableHandle`], which mediates access to the table `taskbar`.
    fn taskbar(&self) -> TaskbarTableHandle<'_>;
}

impl TaskbarTableAccess for super::RemoteTables {
    fn taskbar(&self) -> TaskbarTableHandle<'_> {
        TaskbarTableHandle {
            imp: self.imp.get_table::<Taskbar>("taskbar"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TaskbarInsertCallbackId(__sdk::CallbackId);
pub struct TaskbarDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TaskbarTableHandle<'ctx> {
    type Row = Taskbar;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Taskbar> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TaskbarInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskbarInsertCallbackId {
        TaskbarInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskbarInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TaskbarDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskbarDeleteCallbackId {
        TaskbarDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskbarDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Taskbar>("taskbar");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct TaskbarUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TaskbarTableHandle<'ctx> {
    type UpdateCallbackId = TaskbarUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TaskbarUpdateCallbackId {
        TaskbarUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TaskbarUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Taskbar>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Taskbar>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `taskbar`,
/// which allows point queries on the field of the same name
/// via the [`TaskbarIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.taskbar().id().find(...)`.
pub struct TaskbarIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Taskbar, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TaskbarTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `taskbar`.
    pub fn id(&self) -> TaskbarIdUnique<'ctx> {
        TaskbarIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TaskbarIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Taskbar> {
        self.imp.find(col_val)
    }
}
