// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::__lib;
use spacetimedb_sdk::__codegen::__sats;
use spacetimedb_sdk::__codegen::__ws;
use spacetimedb_sdk::__codegen::{self as __sdk};

use super::taskbar_remote_kind_type::TaskbarRemoteKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Taskbar {
    pub id: __sdk::Identity,
    pub remote: TaskbarRemoteKind,
    pub width: u32,
    pub height: u32,
    pub x: i32,
    pub y: i32,
}

impl __sdk::InModule for Taskbar {
    type Module = super::RemoteModule;
}
